openapi: "3.0.2"

info:
  title: Incident Ticket System API
  version: "1.0.0"

servers:
  - url: https://api.server.test/v1

paths:
  /tickets/create:
    post:
      summary: Create a ticket.
      requestBody:
        description: Information to create a ticket.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketCreateRequest"
      responses:
        200:
          description: Created a ticket. Returns the ID of the created ticket.
          content:
            text/plain:
              schema:
                description: ID of created ticket.
                type: integer
                example: 10

  /tickets/update/{id}:
    put:
      summary: Update a ticket.
      description: >
        Update a ticket by providing new fields to an existing ticket. Users are able to provide
        a new value for every field in the ticket, but some fields can only be updated
        by Admins.
      parameters:
        - name: id
          in: path
          description: ID of ticket to update with new fields.
          required: true
          schema:
            type: integer
            example: 10
      requestBody:
        description: Update to the ticket.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketUpdateRequest"
      responses:
        200:
          description: Successfully updated ticket.
          content:
            text/plain:
              schema:
                description: Success text.
                type: string

  /tickets/{id}: {}

  /tickets: {}
  /tickets/created/{id}: {}
  /tickets/assigned/{id}: {}

components:
  schemas:
    Employee:
      description: An employee.
      type: object
      properties:
        name:
          description: Employee name.
          type: string
        id:
          description: System-assigned employee ID.
          type: integer
        jobTitle:
          description: Text description of job title.
          type: string
        jobLevel:
          description: Job title level for use in auto-severity assignment.
          type: integer
        email:
          description: Employee email.
          type: string
        location:
          description: Text description of location.
          type: string
        admin:
          description: If employee has admin privledges for system.
          type: boolean
        password:
          description: Employee's password for accessing system APIs.
          type: string
          format: password

    Ticket:
      description: A ticket as submitted by a user.
      type: object
      properties:
        # identification metadata
        title:
          description: User-submitted name for ticket.
          example: can't log in
          type: string

        # ticket description
        type:
          description: Type of issue report.
          type: string
          enum:
            - incident-report
            - maintenance
        impactedSystems:
          description: List of system names issue applies to.
          example:
            - server1
            - server2
          type: array
          items:
            type: string
        description:
          description: User-submitted description of the issue.
          example: can't log in, just hangs
          type: string
        comments:
          description: Comments that don't fit in other description fields.
          type: string

        # severity information
        userSeverity:
          description: Severity level assigned by ticket submitter.
          example: 2
          type: integer

        # employee related values
        creator:
          description: ID of employee who submitted this ticket.
          example: 12
          type: integer

    Ticket2:
      description: A ticket as it should exist in the Database. Includes additional fields.
      type: object
      allOf:
        - $ref: "#/components/schemas/Ticket"
        - type: object
          properties:
            # identification metadata
            id:
              description: System assigned ID for ticket.
              type: integer
            creationDate:
              description: Date ticket was created.
              type: string
              format: date-time

            # ticket description
            stepsTaken:
              description: Description field to be filled with actions taken by ticket resolvers.
              type: string

            # severity information
            adminSeverity:
              description: Severtity level assigned by admin.
              type: integer

            # status values
            status:
              description: Text status of this ticket.
              type: string
            opened:
              description: Open/closed state of ticket.
              type: boolean
            lastUpdateTime:
              description: Last time this ticket was updated.
              type: string
              format: date-time

            # employee related values
            assignedEmployees:
              description: List of employee IDs that have been assigned to resolve this ticket.
              type: array
              items:
                type: integer

    TicketCreateRequest:
      description: >
        Ticket with required fields. Represents required fields for user to create a ticket.
      type: object
      allOf:
        - $ref: "#/components/schemas/Ticket"
        - type: object
          required:
            - title
            - type
            - creator

    TicketUpdateRequest:
      description: >
        Request to update a ticket. Includes identifying information for the user attempting
        to perform an update. Regular users are only allowed to update tickets if they own the
        ticket, or they were assigned to the ticket. Admins can update any ticket.
      type: object
      properties:
        employeeId:
          description: ID of the employee performing an update.
          type: integer
        password:
          description: Password of the employee to verify identity.
          type: string
          format: password
        updateTicket:
          description: >
            Ticket update details. Updater can attempt to replace any field, however some fields
            are only allowed to be updated by admins.
          $ref: "#/components/schemas/Ticket2"